package org.app.model;
// Generated 11 Oct, 2014 7:05:20 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="test_db"
)
public class Admin  implements java.io.Serializable {


     private int adminId;
     private String adminPass;

    public Admin() {
    }

	
    public Admin(int adminId) {
        this.adminId = adminId;
    }
    public Admin(int adminId, String adminPass) {
       this.adminId = adminId;
       this.adminPass = adminPass;
    }
   
     @Id 

    
    @Column(name="Admin_Id", unique=true, nullable=false)
    public int getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }

    
    @Column(name="Admin_Pass", length=15)
    public String getAdminPass() {
        return this.adminPass;
    }
    
    public void setAdminPass(String adminPass) {
        this.adminPass = adminPass;
    }




}


